"""add content_hash to news_item

Revision ID: 337c49cec230
Revises: 484c0227e489
Create Date: 2026-09-21 03:23:21.160095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337c49cec230'
down_revision: Union[str, Sequence[str], None] = '484c0227e489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_item', sa.Column('content_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_item', 'content_hash')
    # ### end Alembic commands ###
