"""add scoring_attempts to news_item

Revision ID: c78eff2b73ab
Revises: e1e8142afbb4
Create Date: 2026-09-22 03:55:08.641613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78eff2b73ab'
down_revision: Union[str, Sequence[str], None] = 'e1e8142afbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_item', sa.Column('scoring_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_item', 'scoring_attempts')
    # ### end Alembic commands ###
