"""add classification_attempts to news_item

Revision ID: e1e8142afbb4
Revises: 337c49cec230
Create Date: 2026-09-21 18:23:19.827090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e8142afbb4'
down_revision: Union[str, Sequence[str], None] = '337c49cec230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'news_item',
        sa.Column('classification_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_item', 'classification_attempts')
    # ### end Alembic commands ###
